### ISSUE TITLE
Support for Map/Reduce queries 

### ISSUE THREAD

**Issue by rudasn** [ArnoSaine/react-pouchdb#8]
There's no mention of support for map/reduce queries in the docs so I was wondering if it's supported or not.

Where should one start looking if they were to add this feature?

Thanks 👍

**Comment by ArnoSaine** [comment]
Hi!

Support for Map/Reduce queries was thought to be outside of the scope of this project because Map/Reduce queries do not support live updates.

It might be a good idea to add the support anyway, but for now you can use `useDB` to get PouchDB instance, and `db.query`, `useEffect` and `useState` or promise hook like `react-use-promise`:
```js
import { useDB } from 'react-pouchdb';
import usePromise from 'react-use-promise';

function Query() {
  const db = useDB();
  const [result] = usePromise(() =>
    db.query('index', {
      key: 'Lisa Says',
      include_docs: true
    }), []);
  return <pre>{JSON.stringify(result, null, 2)}</pre>;
}
```

**Comment by rudasn** [comment]
Thanks, I'll give it try 👍
